import type { GravityRule } from './types.js';

const vue = ['*.vue'];
const vueTs = ['*.vue', '*.ts', '*.tsx'];
const vueTsJs = ['*.vue', '*.ts', '*.js'];

export const defaultRules: GravityRule[] = [
  // ── API Alignment ──
  {
    id: 'api-no-react-hooks',
    name: 'No React Hooks',
    category: 'api-alignment',
    severity: 'error',
    enabled: true,
    filePatterns: vueTs,
    block: 'script',
    patterns: [/\b(useState|useEffect|useContext|useReducer|useMemo|useCallback|useRef|useLayoutEffect)\s*\(/],
    message: '检测到 React Hooks — Vue 项目应使用 Composition API',
    suggestion: '使用 ref() / computed() / watch() / onMounted() 替代',
  },
  {
    id: 'api-no-react-import',
    name: 'No React Import',
    category: 'api-alignment',
    severity: 'error',
    enabled: true,
    filePatterns: vueTs,
    block: 'script',
    patterns: [/\bfrom\s+['"]react['"]/, /\bimport\s+.*['"]react-dom['"]/],
    message: '检测到 React 导入 — Vue 项目不应依赖 React',
    suggestion: '移除 react / react-dom 依赖，使用 Vue 等效模块',
  },
  {
    id: 'api-no-vue2-api',
    name: 'No Vue 2 API',
    category: 'api-alignment',
    severity: 'error',
    enabled: true,
    filePatterns: vueTsJs,
    block: 'script',
    patterns: [
      /\bthis\.\$listeners\b/,
      /\bthis\.\$children\b/,
      /\bthis\.\$set\s*\(/,
      /\bthis\.\$on\s*\(/,
      /\bthis\.\$once\s*\(/,
      /\bthis\.\$off\s*\(/,
      /\bVue\.extend\s*\(/,
      /\bnew\s+Vue\s*\(/,
    ],
    message: '检测到 Vue 2 废弃 API — 请使用 Vue 3 等效写法',
    suggestion: 'this.$listeners → useAttrs(); this.$set → reactive(); Vue.extend() → defineComponent()',
  },
  {
    id: 'api-no-vue2-filters',
    name: 'No Vue 2 Filters',
    category: 'api-alignment',
    severity: 'error',
    enabled: true,
    filePatterns: vueTsJs,
    block: 'script',
    patterns: [/\bVue\.filter\s*\(/],
    message: '检测到 Vue 2 过滤器语法 — Vue 3 已移除 filters',
    suggestion: '使用 computed 属性或方法函数替代过滤器',
  },
  {
    id: 'template-no-filter-pipe',
    name: 'No Template Filter Pipe',
    category: 'api-alignment',
    severity: 'error',
    enabled: true,
    filePatterns: vue,
    block: 'template',
    patterns: [/\{\{[^}]*\|\s*\w+/],
    message: '检测到模板管道过滤器语法 — Vue 3 已移除 filters',
    suggestion: '{{ value | filter }} → {{ filter(value) }}',
    docsUrl: 'https://v3-migration.vuejs.org/breaking-changes/filters.html',
  },
  {
    id: 'template-no-classname',
    name: 'No className in Vue Templates',
    category: 'api-alignment',
    severity: 'error',
    enabled: true,
    filePatterns: vue,
    block: 'template',
    patterns: [/\bclassName\s*=/],
    message: '检测到 className — Vue 模板应使用 class',
    suggestion: '将 className="..." 替换为 class="..."',
  },
  {
    id: 'api-no-react-jsx',
    name: 'No React JSX Return',
    category: 'api-alignment',
    severity: 'warning',
    enabled: true,
    filePatterns: ['*.vue', '*.tsx'],
    block: 'script',
    patterns: [/\breturn\s*<[A-Z]/],
    message: '检测到 JSX 返回语法 — Vue 使用模板而非 JSX',
    suggestion: '将 JSX return 替换为 Vue <template> 块',
  },

  // ── Reactivity ──
  {
    id: 'reactivity-no-static-ref',
    name: 'No Static Ref',
    category: 'reactivity',
    severity: 'warning',
    enabled: true,
    filePatterns: vueTs,
    block: 'script',
    patterns: [/\b(ref|reactive)\s*\(\s*\{[^}]*,[^}]*,[^}]/],
    message: '静态配置对象不需要响应式 — 使用 Object.freeze() 或直接声明',
    suggestion: '将 ref({ ... }) / reactive({ ... }) 替换为 Object.freeze({ ... }) 或直接常量声明',
  },
  {
    id: 'reactivity-no-mutation-in-computed',
    name: 'No Mutation in Computed',
    category: 'reactivity',
    severity: 'error',
    enabled: true,
    filePatterns: vueTs,
    block: 'script',
    patterns: [/\bcomputed\s*\(\s*(\(\)\s*=>|\(?\s*\w+\s*\)?)\s*\{[^}]*\.\w+\s*=/],
    message: 'computed 内部不应产生副作用 — 使用 watch 或 watchEffect',
    suggestion: 'computed 应仅返回派生值，副作用操作移到 watch() 或 watchEffect() 中',
  },
  {
    id: 'reactivity-prefer-ref-for-primitives',
    name: 'Prefer Ref for Primitives',
    category: 'reactivity',
    severity: 'info',
    enabled: true,
    filePatterns: vueTs,
    block: 'script',
    patterns: [/\breactive\s*\(\s*(\d+|'[^']*'|"[^"]*"|`[^`]*`|true|false|null)\s*\)/],
    message: '基本类型建议使用 ref() 而非 reactive()',
    suggestion: '将 reactive(0) 替换为 ref(0)，对基本类型更合适且不会丢失响应性',
  },
  {
    id: 'reactivity-no-destructure-props',
    name: 'No Destructure Props',
    category: 'reactivity',
    severity: 'warning',
    enabled: true,
    filePatterns: vue,
    block: 'script',
    patterns: [/\bconst\s*\{[^}]+\}\s*=\s*props\b/],
    message: '直接解构 props 会丢失响应性 — 使用 toRefs(props) 或通过 props.x 访问',
    suggestion: '使用 const { title, count } = toRefs(props) 或直接通过 props.x 访问',
  },

  // ── Template ──
  {
    id: 'template-no-vmodel-value',
    name: 'No v-model:value',
    category: 'template',
    severity: 'error',
    enabled: true,
    filePatterns: vue,
    block: 'template',
    patterns: [/\bv-model:value\b/],
    message: 'v-model:value 已废弃 — 使用 v-model 或 v-model:argument',
    suggestion: 'v-model:value="x" → v-model="x" 或 v-model:modelValue="x"',
  },
  {
    id: 'template-no-vfor-vif',
    name: 'No v-for with v-if',
    category: 'template',
    severity: 'error',
    enabled: true,
    filePatterns: vue,
    block: 'template',
    patterns: [/\bv-for\b[^>]*\bv-if\b/, /\bv-if\b[^>]*\bv-for\b/],
    message: 'v-for 和 v-if 不应在同一元素上 — 优先级 v-if > v-for 会导致行为异常',
    suggestion: '将 v-if 移到 <template> 包装元素上，或使用 computed 过滤列表',
  },
  {
    id: 'template-vfor-key',
    name: 'v-for Missing Key',
    category: 'template',
    severity: 'warning',
    enabled: true,
    filePatterns: vue,
    block: 'template',
    patterns: [/\bv-for="[^"]+"\s*(?!.*:key)[^>]*>/],
    message: 'v-for 缺少 :key — 列表渲染必须提供唯一稳定的 key',
    suggestion: '为 v-for 元素添加 :key="item.id" 或其他唯一标识',
  },
  {
    id: 'template-no-vhtml',
    name: 'No v-html',
    category: 'template',
    severity: 'warning',
    enabled: true,
    filePatterns: vue,
    block: 'template',
    patterns: [/\bv-html\b/],
    message: 'v-html 存在 XSS 风险 — 确保内容已转义或来自可信源',
    suggestion: '避免使用 v-html，或确保内容经过 DOMPurify 等库净化',
  },
  {
    id: 'template-event-casing',
    name: 'Event Casing',
    category: 'template',
    severity: 'info',
    enabled: true,
    filePatterns: vue,
    block: 'template',
    patterns: [/@[a-z]+[A-Z]\w*/],
    message: '模板中事件名建议使用 kebab-case',
    suggestion: '将 @onClick 改为 @click，@myEvent 改为 @my-event',
  },

  // ── Styles ──
  {
    id: 'styles-no-deep-deprecated',
    name: 'No Deprecated Deep Selector',
    category: 'styles',
    severity: 'error',
    enabled: true,
    filePatterns: vue,
    block: 'style',
    patterns: [/(?<!\w)>>>\s*\./, /(?<!\w)\/deep\/\s*\./, /(?<!\w)::v-deep\s*\./],
    message: '检测到废弃的深度选择器 — 使用 :deep() 替代',
    suggestion: '>>> .child → :deep(.child)',
  },
  {
    id: 'styles-prefer-scoped',
    name: 'Prefer Scoped Styles',
    category: 'styles',
    severity: 'info',
    enabled: true,
    filePatterns: vue,
    block: 'style',
    patterns: [/<style(?=[\s>])(?!\s*(?:scoped|module)[\s>])[^>]*>/],
    message: '<style> 未使用 scoped — 建议添加 scoped 避免样式污染',
    suggestion: '<style> → <style scoped>',
  },

  // ── Performance ──
  {
    id: 'perf-no-async-in-computed',
    name: 'No Async in Computed',
    category: 'performance',
    severity: 'error',
    enabled: true,
    filePatterns: vueTs,
    block: 'script',
    patterns: [/\bcomputed\s*\(\s*async\s*\(/],
    message: 'computed 不支持异步操作 — 使用 watch 或 watchEffect',
    suggestion: '将 computed 中的异步逻辑移到 watch() 或 watchEffect() 中',
  },
  {
    id: 'perf-no-sync-in-watch',
    name: 'No Sync in Watch',
    category: 'performance',
    severity: 'info',
    enabled: true,
    filePatterns: vueTs,
    block: 'script',
    patterns: [/\bwatch\s*\([^)]*,\s*async\s*\(/],
    message: 'watch 中的异步操作可能在 DOM 更新后执行 — 注意 flush 选项',
    suggestion: '考虑使用 flush: "pre" 或 flush: "post" 控制 watch 回调的执行时机',
  },
];
